In [1]:

import numpy as np

In [4]:
a = np.arange(0,5)
b = np.arange(6,11)
c = np.arange(11,16)
d = np.arange(16,21)

print(a)
print(b)
print(c)
print(d)

[0 1 2 3 4]
[ 6  7  8  9 10]
[11 12 13 14 15]
[16 17 18 19 20]


In [5]:
a = list(map(int,input("Enter 5 Values A : ").split(',')))
b = list(map(int,input("Enter 5 Values B : ").split(',')))
c = list(map(int,input("Enter 5 Values C : ").split(',')))
d = list(map(int,input("Enter 5 Values D : ").split(',')))
print(a)
print(b)
print(c)
print(d)

KeyboardInterrupt: Interrupted by user