In [154]:
import numpy as np
from sympy import limit,sqrt,pprint,diff
from sympy.abc import x,y

from sympy.solvers import solve
import numpy.linalg as la
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [155]:
df = pd.read_csv('Housing.csv')
df

price  lotsize  bedrooms  bathrms  stories driveway recroom fullbase  \
0     42000.0     5850         3        1        2      yes      no      yes   
1     38500.0     4000         2        1        1      yes      no       no   
2     49500.0     3060         3        1        1      yes      no       no   
3     60500.0     6650         3        1        2      yes     yes       no   
4     61000.0     6360         2        1        1      yes      no       no   
..        ...      ...       ...      ...      ...      ...     ...      ...   
541   91500.0     4800         3        2        4      yes     yes       no   
542   94000.0     6000         3        2        4      yes      no       no   
543  103000.0     6000         3        2        4      yes     yes       no   
544  105000.0     6000         3        2        2      yes     yes       no   
545  105000.0     6000         3        1        2      yes      no       no   

    gashw airco  garagepl prefarea  
0      no    no         1       no  
1      no    no         0       no  
2      no    no         0       no  
3      no    no         0       no  
4      no    no         0       no  
..    ...   ...       ...      ...  
541    no   yes         0       no  
542    no   yes         0       no  
543    no   yes         1       no  
544    no   yes         1       no  
545    no   yes         1       no  

[546 rows x 12 columns]

In [156]:
xi = df['lotsize']
yi = df['price']

In [157]:
xi = df['lotsize']
yi = df['price']


n = len(xi)
sxi = np.sum(xi)
syi = np.sum(yi)
sxi2 = np.sum(xi*xi)
sxiyi = np.sum(xi*yi)

a = np.array([[n,sxi],
             [sxi,sxi2]])
b = np.array([syi,sxiyi])
             
print("Solution : \n ",la.solve(a,b))
b= la.solve(a,b)

Solution : 
  [3.41361916e+04 6.59876759e+00]


In [158]:
z = (np.sum((yi-(b[0] + b[1]*xi))**2))
z
# ycap = b[0] + b[1]*xi
# z = np.sum((yi-ycap)**2)  # Cost/Error Function for 1 independant and 1 dependant 
# z

277043862881.1533

In [159]:
df['driveway'].replace({'yes' : True,'no':False},inplace=True)

In [160]:
df

price  lotsize  bedrooms  bathrms  stories  driveway recroom fullbase  \
0     42000.0     5850         3        1        2      True      no      yes   
1     38500.0     4000         2        1        1      True      no       no   
2     49500.0     3060         3        1        1      True      no       no   
3     60500.0     6650         3        1        2      True     yes       no   
4     61000.0     6360         2        1        1      True      no       no   
..        ...      ...       ...      ...      ...       ...     ...      ...   
541   91500.0     4800         3        2        4      True     yes       no   
542   94000.0     6000         3        2        4      True      no       no   
543  103000.0     6000         3        2        4      True     yes       no   
544  105000.0     6000         3        2        2      True     yes       no   
545  105000.0     6000         3        1        2      True      no       no   

    gashw airco  garagepl prefarea  
0      no    no         1       no  
1      no    no         0       no  
2      no    no         0       no  
3      no    no         0       no  
4      no    no         0       no  
..    ...   ...       ...      ...  
541    no   yes         0       no  
542    no   yes         0       no  
543    no   yes         1       no  
544    no   yes         1       no  
545    no   yes         1       no  

[546 rows x 12 columns]

In [161]:
x1 = df['lotsize']
x2 = df['driveway']
y = df['price']

n = len(x1)
sx1 = np.sum(x1)
sx2 = np.sum(x2)
sy = np.sum(y)
sx1x2 = np.sum(x1*x2)
sx1x1 = np.sum(x1**2)
sx2x2 = np.sum(x2**2)
sx1y = np.sum(x1*y)
sx2y = np.sum(x2*y)

a = np.array([[n , sx1 , sx2],
              [sx1 , sx1x1 , sx1x2],
              [sx2 , sx1x2 , sx2x2]])
b = np.array([sy , sx1y , sx2y ])

print("Solution : \n ",la.solve(a,b))
b = la.solve(a,b)
b

Solution : 
  [2.67509411e+04 6.04608109e+00 1.19115694e+04]


array([2.67509411e+04, 6.04608109e+00, 1.19115694e+04])

In [162]:
ycap = b[0]+b[1]*x1+b[2]*x2

z = np.sum((y-ycap)**2) # Cost/Error Function for 2 independant and 1 dependant 
z

268442005045.18875

In [163]:
x1 = df['lotsize']
x2 = df['driveway']
x3 = df['bedrooms']
y = df['price']

n = len(x1)
sx1 = np.sum(x1)
sx2 = np.sum(x2)
sx3 = np.sum(x3)

sx1x2 = np.sum(x1*x2)
sx1x1 = np.sum(x1**2)
sx2x2 = np.sum(x2**2)


sx1x3 = np.sum(x1*x3)
sx2x3 = np.sum(x2*x3)
sx3x3 = np.sum(x3*x3)

sy = np.sum(y)
sx1y = np.sum(x1*y)
sx2y = np.sum(x2*y)
sx3y = np.sum(x3*y)

a = np.array([[n , sx1 , sx2, sx3],
              [sx1 , sx1x1 , sx1x2 , sx1x3],
              [sx2 , sx1x2 , sx2x2 , sx2x3],
              [sx3, sx1x3 , sx2x3 , sx3x3]])
b = np.array([sy , sx1y , sx2y , sx3y])

print("Solution : \n ",la.solve(a,b))
b = la.solve(a,b)
b


Solution : 
  [-3.61744978e+03  5.41636859e+00  1.33208107e+04  1.09271076e+04]


array([-3.61744978e+03,  5.41636859e+00,  1.33208107e+04,  1.09271076e+04])

In [164]:
ycap = b[0]+b[1]*x1+b[2]*x2 + b[3]*x3

z = np.sum((y-ycap)**2)
z

233994951113.40485

In [165]:
x1 = df['lotsize']
x2 = df['driveway']
x3 = df['stories']
x4 = df['bedrooms']
y = df['price']

n = len(x1)
sx1 = np.sum(x1)
sx2 = np.sum(x2)
sx3 = np.sum(x3)
sx4 = np.sum(x4)

sx1x2 = np.sum(x1*x2)
sx1x1 = np.sum(x1**2)
sx2x2 = np.sum(x2**2)



sx1x3 = np.sum(x1*x3)
sx2x3 = np.sum(x2*x3)
sx3x3 = np.sum(x3*x3)

sy = np.sum(y)
sx1y = np.sum(x1*y)
sx2y = np.sum(x2*y)
sx3y = np.sum(x3*y)
sx4y = np.sum(x4*y)

sx1x4 = np.sum(x1*x4)
sx2x4 = np.sum(x2*x4)
sx3x4 = np.sum(x3*x4)
sx4x4 = np.sum(x4*x4)

a = np.array([[n , sx1 , sx2, sx3 , sx4],
              [sx1 , sx1x1 , sx1x2 , sx1x3 , sx1x4],
              [sx2 , sx1x2 , sx2x2 , sx2x3 , sx2x4],
              [sx3, sx1x3 , sx2x3 , sx3x3 , sx3x4],
              [sx4 , sx1x4 , sx2x4 , sx3x4 , sx4x4]])
b = np.array([sy , sx1y , sx2y , sx3y , sx4y])

print("Solution : \n ",la.solve(a,b))
b = la.solve(a,b)
b


Solution : 
  [-4.70752681e+03  5.47839297e+00  1.03399901e+04  9.03405381e+03
  6.54301890e+03]


array([-4.70752681e+03,  5.47839297e+00,  1.03399901e+04,  9.03405381e+03,
        6.54301890e+03])

In [166]:
ycap = b[0]+b[1]*x1+b[2]*x2 + b[3]*x3 + b[4]*x4

z = np.sum((y-ycap)**2)
z

206600670428.50153

In [167]:
x1 = df['lotsize']
x2 = df['driveway']
x3 = df['stories']
x4 = df['bedrooms']
x5 = df['bathrms']

y = df['price']

n = len(x1)
sx1 = np.sum(x1)
sx2 = np.sum(x2)
sx3 = np.sum(x3)
sx4 = np.sum(x4)

sx1x2 = np.sum(x1*x2)
sx1x1 = np.sum(x1**2)
sx2x2 = np.sum(x2**2)



sx1x3 = np.sum(x1*x3)
sx2x3 = np.sum(x2*x3)
sx3x3 = np.sum(x3*x3)

sy = np.sum(y)
sx1y = np.sum(x1*y)
sx2y = np.sum(x2*y)
sx3y = np.sum(x3*y)
sx4y = np.sum(x4*y)
sx5y = np.sum(x5*y)

sx1x4 = np.sum(x1*x4)
sx2x4 = np.sum(x2*x4)
sx3x4 = np.sum(x3*x4)
sx4x4 = np.sum(x4*x4)

sx5 = np.sum(x5)
sx1x5 = np.sum(x1*x5)
sx2x5 = np.sum(x2*x5)
sx3x5 = np.sum(x3*x5)
sx4x5 = np.sum(x4*x5)
sx5x5 = np.sum(x5*x5)

a = np.array([[n , sx1 , sx2, sx3 , sx4 , sx5],
              [sx1 , sx1x1 , sx1x2 , sx1x3 , sx1x4 , sx1x5],
              [sx2 , sx1x2 , sx2x2 , sx2x3 , sx2x4 , sx2x5],
              [sx3, sx1x3 , sx2x3 , sx3x3 , sx3x4 , sx3x5],
              [sx4 , sx1x4 , sx2x4 , sx3x4 , sx4x4 , sx4x5],
              [sx5 , sx1x5 , sx2x5 , sx3x5 , sx4x5 , sx5x5]])
b = np.array([sy , sx1y , sx2y , sx3y , sx4y , sx5y])

print("Solution : \n ",la.solve(a,b))
b = la.solve(a,b)
b


Solution : 
  [-1.13795840e+04  4.91011379e+00  1.08627137e+04  6.98164030e+03
  3.38703940e+03  1.72807342e+04]


array([-1.13795840e+04,  4.91011379e+00,  1.08627137e+04,  6.98164030e+03,
        3.38703940e+03,  1.72807342e+04])

In [168]:
ycap = b[0]+b[1]*x1+b[2]*x2 + b[3]*x3 + b[4]*x4 + b[5]*x5

z = np.sum((y-ycap)**2)
z

173499256697.40796

#######################################################################################

In [169]:
df.head(1)

price  lotsize  bedrooms  bathrms  stories  driveway recroom fullbase  \
0  42000.0     5850         3        1        2      True      no      yes   

  gashw airco  garagepl prefarea  
0    no    no         1       no

In [170]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
x = df[['lotsize','driveway','bedrooms']]
y = df['price']

In [171]:
lr.fit(x,y)
print("Intercept : ",lr.intercept_)
print("cofficient",lr.coef_)
b = lr.coef_
k = lr.intercept_

Intercept :  -3617.449779897448
cofficient [5.41636859e+00 1.33208107e+04 1.09271076e+04]


In [172]:
ycap = k+b[0]*x1+b[1]*x2 + b[2]*x3 

z = np.sum((y-ycap)**2)
z

305515180751.9358

In [173]:
df.head(1)

price  lotsize  bedrooms  bathrms  stories  driveway recroom fullbase  \
0  42000.0     5850         3        1        2      True      no      yes   

  gashw airco  garagepl prefarea  
0    no    no         1       no

In [174]:
df['fullbase'].replace({'yes':True,'no':False},inplace=True)
df['recroom'].replace({'yes':True,'no':False},inplace=True)
df['gashw'].replace({'yes':True,'no':False},inplace=True)
df['airco'].replace({'yes':True,'no':False},inplace=True)
df['prefarea'].replace({'yes':True,'no':False},inplace=True)
df



price  lotsize  bedrooms  bathrms  stories  driveway  recroom  \
0     42000.0     5850         3        1        2      True    False   
1     38500.0     4000         2        1        1      True    False   
2     49500.0     3060         3        1        1      True    False   
3     60500.0     6650         3        1        2      True     True   
4     61000.0     6360         2        1        1      True    False   
..        ...      ...       ...      ...      ...       ...      ...   
541   91500.0     4800         3        2        4      True     True   
542   94000.0     6000         3        2        4      True    False   
543  103000.0     6000         3        2        4      True     True   
544  105000.0     6000         3        2        2      True     True   
545  105000.0     6000         3        1        2      True    False   

     fullbase  gashw  airco  garagepl  prefarea  
0        True  False  False         1     False  
1       False  False  False         0     False  
2       False  False  False         0     False  
3       False  False  False         0     False  
4       False  False  False         0     False  
..        ...    ...    ...       ...       ...  
541     False  False   True         0     False  
542     False  False   True         0     False  
543     False  False   True         1     False  
544     False  False   True         1     False  
545     False  False   True         1     False  

[546 rows x 12 columns]

In [175]:
y = df['price']
x = df.drop('price',axis=1)
x.head()

lotsize  bedrooms  bathrms  stories  driveway  recroom  fullbase  gashw  \
0     5850         3        1        2      True    False      True  False   
1     4000         2        1        1      True    False     False  False   
2     3060         3        1        1      True    False     False  False   
3     6650         3        1        2      True     True     False  False   
4     6360         2        1        1      True    False     False  False   

   airco  garagepl  prefarea  
0  False         1     False  
1  False         0     False  
2  False         0     False  
3  False         0     False  
4  False         0     False

In [176]:
lr.fit(x,y)
print("Intercept : ",lr.intercept_)
print("cofficient",lr.coef_)

Intercept :  -4038.3504250983824
cofficient [3.54630297e+00 1.83200347e+03 1.43355585e+04 6.55694571e+03
 6.68777889e+03 4.51128383e+03 5.45238554e+03 1.28314063e+04
 1.26328904e+04 4.24482900e+03 9.36951324e+03]


In [177]:
ycap = lr.predict(x)
z = np.mean((y-ycap)**2)
z

232646651.36349452

## gradient descent