In [1]:
import numpy as np
from numpy import linalg as la 
from sklearn.decomposition import PCA

### Single Value Decomposition

In [2]:
a = np.array([[2,0,8,6,0],
             [1,6,0,1,7],
             [5,0,7,4,0],
             [7,0,8,5,0],
             [0,10,0,0,7]])

print("Shape : ",a.shape)
U,S,VT = la.svd(a)
#factors of given array 
print("U : \n",U)
print("U Shape :\n",U.shape)
print("S:\n",S)
print("VT:\n",VT)
print("VT Shape :\n",VT.shape)

pca = PCA()
pca.fit_transform(a)

Shape :  (5, 5)
U : 
 [[-0.54225536  0.06499573  0.82161708  0.10574661 -0.12448979]
 [-0.10181247 -0.59346055 -0.11255162  0.78812338  0.06026999]
 [-0.52495325  0.05938171 -0.21296861 -0.11574223  0.81372354]
 [-0.64487038  0.07040626 -0.50874368 -0.05990271 -0.56282918]
 [-0.06449519 -0.79692967  0.09000966 -0.59219473 -0.04412631]]
U Shape :
 (5, 5)
S:
 [17.91837086 15.17137188  3.56400204  1.98422815  0.34955567]
VT:
 [[-4.64617132e-01 -7.00859862e-02 -7.35093538e-01 -4.84391665e-01
  -6.49698348e-02]
 [ 2.15065094e-02 -7.59987964e-01  9.87971197e-02  2.54473982e-02
  -6.41519543e-01]
 [-8.68508563e-01  6.30714767e-02  2.84008516e-01  3.98865659e-01
  -4.42743085e-02]
 [ 7.99553843e-04 -6.01345670e-01 -2.23484573e-01  3.32683813e-01
   6.91201036e-01]
 [-1.71349432e-01 -2.27841223e-01  5.65040200e-01 -7.03523142e-01
   3.23283947e-01]]
VT Shape :
 (5, 5)


array([[-5.47704021e+00,  2.90525283e+00, -5.56039026e-02,
        -1.96073316e-01,  3.20607035e-16],
       [ 7.24789656e+00, -2.61731466e-01,  1.68935626e+00,
        -1.59898341e-01,  3.20607035e-16],
       [-5.22762970e+00, -6.82671247e-01,  1.89162817e-01,
         8.06266183e-01,  3.20607035e-16],
       [-6.65621724e+00, -2.03172957e+00, -4.09987936e-01,
        -5.27974287e-01,  3.20607035e-16],
       [ 1.01129906e+01,  7.08794554e-02, -1.41292724e+00,
         7.76797608e-02,  3.20607035e-16]])

### Variance Covariance Matrix 

In [3]:
print("\nQ1----------------\n")
x = np.array([2,5,7,8])
y = np.array([9,7,5,2,])
data = np.stack((x,y) , axis=0)
print(data)
print(np.cov(data , ddof=0))

print("\nQ2----------------\n")
x = np.array([2,5,7,8])
y = np.array([3,10,18,24])
data = np.stack((x,y) , axis=0)
print(data)
print(np.cov(data , ddof=0))


Q1----------------

[[2 5 7 8]
 [9 7 5 2]]
[[ 5.25   -5.625 ]
 [-5.625   6.6875]]

Q2----------------

[[ 2  5  7  8]
 [ 3 10 18 24]]
[[ 5.25   17.875 ]
 [17.875  63.1875]]
