In [251]:
import numpy as np
import pandas as pd

In [252]:
np.show_config()

Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /usr/local/include
    lib directory: /usr/local/lib
    name: openblas64
    openblas configuration: USE_64BITINT=1 DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= SKYLAKEX MAX_THREADS=2
    pc file directory: /usr/local/lib/pkgconfig
    version: 0.3.23.dev
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /usr/local/include
    lib directory: /usr/local/lib
    name: openblas64
    openblas configuration: USE_64BITINT=1 DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= SKYLAKEX MAX_THREADS=2
    pc file directory: /usr/local/lib/pkgconfig
    version: 0.3.23.dev
Compilers:
  c:
    commands: cc
    linker: ld.bfd
    name: gcc
    version: 10.2.1
  c++:
    commands: c++
    linker: ld.bfd
    name: gcc
    version: 10.2.1
  cython:
    commands: cython
    linker:

In [253]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

In [254]:
np.version.full_version

'1.26.0'

In [255]:
a = np.arange(1,5)

In [256]:
a

array([1, 2, 3, 4])

In [257]:
[a==0]

[array([False, False, False, False])]

In [258]:
[a!=0]

[array([ True,  True,  True,  True])]

In [259]:
print('orignal array \n',a)

print('weather all of the elements in array are zero\n',a.all(where=a==0))

orignal array 
 [1 2 3 4]
weather all of the elements in array are zero
 True


In [260]:
b = np.zeros(5,dtype=int)
print('orignal array \n',b)
print('weather any of the elements in array are non-zero\n',b.any(where=b!=0))

orignal array 
 [0 0 0 0 0]
weather any of the elements in array are non-zero
 False


In [261]:
print("To check infinite or nan values : ")
a = np.array([0,1.5,0,np.nan,np.inf])
print(a)
np.isfinite(a)


To check infinite or nan values : 
[0.  1.5 0.  nan inf]


array([ True,  True,  True, False, False])

In [262]:
a.any(where=np.isfinite(a))

True

In [263]:
a.any(where=np.isnan(a))

True

In [264]:
np.isreal(k)

array([ True,  True,  True,  True,  True,  True])

In [265]:
a = np.array([4,7,3,2,5])
b = np.array([4,3,2,1,7])
a,b

(array([4, 7, 3, 2, 5]), array([4, 3, 2, 1, 7]))

In [266]:
[a>b]

[array([False,  True,  True,  True, False])]

In [267]:
[a>=b]

[array([ True,  True,  True,  True, False])]

In [268]:
[a<=b]

[array([ True, False, False, False,  True])]

In [269]:
[a==b]

[array([ True, False, False, False, False])]

In [270]:
# Write a NumPy program to create an array with the values 1, 7, 13, 105 and determine the size of
# the memory occupied by the array.

In [271]:
z = np.array([1,7,13,105])
z.itemsize*len(z)

32

In [272]:
# Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives.
a = np.zeros(10,dtype=int)
a

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [273]:
a = np.ones(10,dtype=int)
a

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [274]:
a = np.array([5 for i in range(10)])
a

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [275]:
a = np.full(shape=10,fill_value=5)
a

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [276]:
a = np.arange(30,50.5,dtype=int)
a

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46,
       47, 48, 49, 50])

In [277]:
a = np.arange(30,50.5,dtype=int,step=2)
a

array([30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50])

In [278]:
a = np.identity(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [279]:
a = np.random.ranf(1)
a

array([0.3716833])

In [280]:
a = np.random.normal(0,1,15)
a

array([-2.41036104,  0.1512654 , -0.25103731, -0.60197716,  1.28084043,
       -1.92608569, -0.1921793 , -0.22538299,  0.1344504 , -0.09068158,
        2.17865326,  0.76495436, -1.31084297,  1.54155925, -0.80286239])

In [281]:
v = np.arange(15,55)
print('orignal vextor\n',v)
print("values of range 15-55 except frist and last")
v[1:]

orignal vextor
 [15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38
 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54]
values of range 15-55 except frist and last


array([16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32,
       33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49,
       50, 51, 52, 53, 54])

Write a NumPy program to create a 3X4 array using and iterate over it.

In [282]:
a = np.random.randint(5,15,size=(3,4))
a

array([[ 5, 11,  6, 12],
       [11,  6,  9,  6],
       [12, 12, 11, 11]])

In [283]:
a = np.arange(5,51,5)
a

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [289]:
v = np.arange(0,20)
v

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [290]:

v[(9<v) & (v<15)] = -v[(9<v) & (v<15)]
v

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9, -10, -11, -12,
       -13, -14,  15,  16,  17,  18,  19])

In [294]:
a = np.random.randint(0,10,5)
a

array([6, 8, 8, 5, 8])

In [299]:
arr1 = np.random.randint(0,10,5)
arr2 = np.random.randint(0,10,5)
print(f"{arr1}*{arr2} = {arr1*arr2}")

[6 2 8 8 9]*[3 9 8 7 1] = [18 18 64 56  9]


Write a NumPy program to create a 3x4 matrix filled with values from 10 to 21.

In [301]:
m = np.random.randint(10,20,size=(3,4))
m

array([[10, 17, 19, 10],
       [14, 11, 17, 11],
       [15, 17, 19, 16]])

In [ ]:
s