In [1]:
import numpy as np

In [2]:

a = np.zeros(shape=3)
a

array([0., 0., 0.])

In [3]:
b = np.empty(shape=3)
b

array([0., 0., 0.])

In [4]:
b = np.arange(0,5)
b

array([0, 1, 2, 3, 4])

In [5]:
b = np.arange(0.4,0.8,0.1)
b

array([0.4, 0.5, 0.6, 0.7])

In [6]:
b = np.arange(0.4,0.7,0.1)
b

array([0.4, 0.5, 0.6])

In [7]:
b = np.arange(0.4,0.755,0.1) # adds last element too
b

array([0.4, 0.5, 0.6, 0.7])

In [8]:
b = np.linspace(0.4,0.7)
b

array([0.4       , 0.40612245, 0.4122449 , 0.41836735, 0.4244898 ,
       0.43061224, 0.43673469, 0.44285714, 0.44897959, 0.45510204,
       0.46122449, 0.46734694, 0.47346939, 0.47959184, 0.48571429,
       0.49183673, 0.49795918, 0.50408163, 0.51020408, 0.51632653,
       0.52244898, 0.52857143, 0.53469388, 0.54081633, 0.54693878,
       0.55306122, 0.55918367, 0.56530612, 0.57142857, 0.57755102,
       0.58367347, 0.58979592, 0.59591837, 0.60204082, 0.60816327,
       0.61428571, 0.62040816, 0.62653061, 0.63265306, 0.63877551,
       0.64489796, 0.65102041, 0.65714286, 0.66326531, 0.66938776,
       0.6755102 , 0.68163265, 0.6877551 , 0.69387755, 0.7       ])

In [9]:
a = np.arange(0,10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
a[2:4]

array([2, 3])

In [11]:
a[:4]

array([0, 1, 2, 3])

In [12]:
a[::4] # works as step 

array([0, 4, 8])

In [13]:
a[[1,3,4]]  

array([1, 3, 4])

In [14]:
a[-2::]

array([8, 9])

In [15]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
b = np.any(a>5)
b

True

In [17]:
b = np.all(a>5)
b

False

In [18]:
a[a>5]

array([6, 7, 8, 9])

In [19]:
a[(a>=3)&(a<=5)]

array([3, 4, 5])

In [20]:
a[(a>=3)&(a<=5)] = 0
a

array([0, 1, 2, 0, 0, 0, 6, 7, 8, 9])