# __Day 12__

## __libraries for data analisys__

* ## __Numpy__

In [165]:
import numpy as np # for maths operation in arrys 

__1 D Array__

In [166]:
a = np.array([12,13,23.78,45]) # np.array is homogueneous 
print(a)
print(type(a)) # type of variable object 
print(a.dtype) # type of data it stores
print(a.ndim) # diamension of array 
print(a.shape) # Shape of Array like 2x2 or 3x3 

[12.   13.   23.78 45.  ]
<class 'numpy.ndarray'>
float64
1
(4,)


In [167]:
a = np.array([['xxx','yyy'],
              ['zzz','ppp']]) # np.array is homogueneous 
print(a)
print(type(a)) # type of variable object 
print(a.dtype) # type of data it stores for str --> U(no_of_char) 
print(a.ndim) # diamension of array 
print(a.shape) # Shape of Array like 2x2 or 3x3 

[['xxx' 'yyy']
 ['zzz' 'ppp']]
<class 'numpy.ndarray'>
<U3
2
(2, 2)


__2 D Array__

In [168]:
a = np.array([[12,13,23,45],
              [22,35,56,75]]) # np.array is homogueneous 
print(a)
print(type(a)) # type of variable object 
print(a.dtype) # type of data it stores
print(a.ndim) # diamension of array 
print(a.shape) # Shape of Array like 2x2 or 3x3 

[[12 13 23 45]
 [22 35 56 75]]
<class 'numpy.ndarray'>
int64
2
(2, 4)


__3 D Array__

In [169]:
a = np.array([[[12,13,23,45],[22,35,56,75],[324,423,253,243]],
              [[12,13,23,45],[22,34,56,75],[324,423,253,243]],
              [[12,13,23,45],[22,32,56,75],[324,423,253,243]],
              [[12,13,23,45],[22,31,56,75],[324,423,253,243]]]) # np.array is homogueneous 
print(a)
print(type(a)) # type of variable object 
print(a.dtype) # type of data it stores
print(a.ndim) # diamension of array 
print(a.shape) # Shape of Array like 2x2 or 3x3 - shape(row,col,value)
print(a[1,1,1]) # priniting nested value in np.array , in list - lst[1][1][1]

[[[ 12  13  23  45]
  [ 22  35  56  75]
  [324 423 253 243]]

 [[ 12  13  23  45]
  [ 22  34  56  75]
  [324 423 253 243]]

 [[ 12  13  23  45]
  [ 22  32  56  75]
  [324 423 253 243]]

 [[ 12  13  23  45]
  [ 22  31  56  75]
  [324 423 253 243]]]
<class 'numpy.ndarray'>
int64
3
(4, 3, 4)
34


* __slicing of matrix__

In [170]:
b  = np.arange(12) # like range (strart,end,step)
print(b) 
c = np.arange(1,32,2).reshape(4,4)
print(c)
print()
print(c[1:3,2:4])  # Slicing # c[rowS:rowE,colS:colE] - rows and col value start with zero 
print()
print(c[0:2,0:2])
print()
print(c[2:4,1:3])
print()
print(c[-2,-3])   # giving postion in reverse manner 
print(c[2,-1]) 

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 1  3  5  7]
 [ 9 11 13 15]
 [17 19 21 23]
 [25 27 29 31]]

[[13 15]
 [21 23]]

[[ 1  3]
 [ 9 11]]

[[19 21]
 [27 29]]

19
23


In [171]:
c = np.arange(1,32,2).reshape(4,4,order='f') # order at which value will be added [ f - vertical c - horizontal ] default horizontal 
c

array([[ 1,  9, 17, 25],
       [ 3, 11, 19, 27],
       [ 5, 13, 21, 29],
       [ 7, 15, 23, 31]])

In [172]:
a = np.zeros((3,3),dtype = 'int') # defalut dtype is float we can use int 
b = np.ones((2,2))
c = np.empty((4,4))
c

array([[4.94e-324, 1.48e-323, 2.47e-323, 3.46e-323],
       [4.45e-323, 5.43e-323, 6.42e-323, 7.41e-323],
       [8.40e-323, 9.39e-323, 1.04e-322, 1.14e-322],
       [1.24e-322, 1.33e-322, 1.43e-322, 1.53e-322]])

In [173]:
b

array([[1., 1.],
       [1., 1.]])

In [174]:
a

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [175]:
a = np.arange(0,9).reshape(3,3)
b = np.arange(10,19).reshape(3,3)
print(a,"\n\n",b)

[[0 1 2]
 [3 4 5]
 [6 7 8]] 

 [[10 11 12]
 [13 14 15]
 [16 17 18]]


In [176]:
c = a + b
c

array([[10, 12, 14],
       [16, 18, 20],
       [22, 24, 26]])

In [177]:
c = a * b # Hadamard Product 
c

array([[  0,  11,  24],
       [ 39,  56,  75],
       [ 96, 119, 144]])

In [178]:
# matrix multiplication
print(a.__matmul__(b))
print()
print(np.matmul(a,b)) 
print()
print(a.dot(b))
print()
print(a@b)

[[ 45  48  51]
 [162 174 186]
 [279 300 321]]

[[ 45  48  51]
 [162 174 186]
 [279 300 321]]

[[ 45  48  51]
 [162 174 186]
 [279 300 321]]

[[ 45  48  51]
 [162 174 186]
 [279 300 321]]


* __To Print Identity Matrix__

In [179]:
a = np.identity(3) # to create identity matrix
a 

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [180]:
b = np.eye(3,4) # non square element identity matrix
c = np.eye(3,4,k=1) # non square element identity matrix - k=1 shifts the 1's above diagonal if k=-1 shifts the 1's below diagonals
d = np.eye(3,4,k=-1)
print(b)
print()
print(c)
print()
print(d)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]

[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

[[0. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]]


* __Filtering of Arry__

In [181]:
a = np.array([[12,13,23,45],[12,13,23,45],[12,13,23,45]])
print(a[a%6==0]) # return values which satisfy the condition
print(a[a>5])

[12 12 12]
[12 13 23 45 12 13 23 45 12 13 23 45]


In [182]:
print(np.where(a%2==0)) # prints as object 
print(list(np.where(a%2==0)[0].data)) # prints data

(array([0, 1, 2]), array([0, 0, 0]))
[0, 1, 2]


In [183]:
print(np.sum(a,axis=1)) # row wise sum
print(np.sum(a,axis=0)) # column wise sum
print(np.sum(a)) # total sum of both rows and columns 

[93 93 93]
[ 36  39  69 135]
279


In [184]:
print(np.mean(a)) # finds mean - Average 
print(np.median(a)) # finds median - center value if arrenged sequentially
#print(np.mode(a)) # mode - highest frequency # not availabe on numpy

23.25
18.0


* __Stack and Vstack__

In [185]:
x = np.array([10,20,30])
y = np.array([11,12,13])
z = np.array([21,22,23])

print(np.hstack((x,y,z))) # stacks the array elements horizontally
print(np.vstack((x,y,z))) # stacks the array elements vertically
d = np.vstack((x,y,z))

[10 20 30 11 12 13 21 22 23]
[[10 20 30]
 [11 12 13]
 [21 22 23]]


In [186]:
np.flip(d) # flips both rows and columns 

array([[23, 22, 21],
       [13, 12, 11],
       [30, 20, 10]])

In [187]:
np.flip(d,axis=0) # reverse the rows

array([[21, 22, 23],
       [11, 12, 13],
       [10, 20, 30]])

In [188]:
np.flip(d,axis=1) # reverse the columns 

array([[30, 20, 10],
       [13, 12, 11],
       [23, 22, 21]])

In [189]:
x = np.linspace(10,30,7,endpoint=False) # find equidistant points between range linespace(start,end,points_needed,endpoint should be added or not)
print(x)

[10.         12.85714286 15.71428571 18.57142857 21.42857143 24.28571429
 27.14285714]


* ## __Scipy__

In [190]:
from scipy.special import cbrt,comb,perm

# cbrt = cuberoot
# comb = combination
# perm = permutaion

In [193]:
x = cbrt([27,64])
print(x)

[3. 4.]


In [194]:
print(perm(6,2))
print(comb(6,2))

30.0
15.0


In [199]:
import numpy as np
from scipy import linalg as la 
# scipy used for scintific calculation and numpy used for numeric calculation 

In [200]:
m = np.array([[10,20],[30,40]])
print(la.det(m))

-200.0


In [214]:
eig_val,eig_vect = la.eig(m)
print(eig_val,"\n",eig_vect)

[-3.72281323+0.j 53.72281323+0.j] 
 [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [215]:
from scipy import stats

In [217]:
m = np.array([[22,23,14,22,56],[22,46,23,15,53]])
modeval = stats.mode(m,axis=0)
print(modeval)

ModeResult(mode=array([[22, 23, 14, 15, 53]]), count=array([[2, 1, 1, 1, 1]]))


/tmp/ipykernel_41400/2338244010.py:2: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  modeval = stats.mode(m,axis=0)


In [218]:
from scipy import integrate

In [220]:
f = lambda x:x**2
integration = integrate.quad(f,0,1)
print(integration)

(0.33333333333333337, 3.700743415417189e-15)


* ## __Pandas__

In [ ]:
import pandas